version = 0.1
[default.deploy.parameters]
stack_name = "motivador-app-bff"
resolve_s3 = true
s3_prefix = "motivador-app-bff"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
